// Aplikacja/ReactApp/oto-auto/src/components/forms/create-offer-form/create-offer-form.tsx
import './create-offer-form.scss';
import { useFormik } from "formik";
import { InputText } from "primereact/inputtext";
import { SelectButton } from 'primereact/selectbutton';
import { InputTextarea } from 'primereact/inputtextarea';
import { BasicInfoForm, CreateOfferFormStateModel, DealerDataForm, MainFeaturesForm, PriceDataForm, TechnicalDataForm, VehicleDescriptionForm } from "../../../redux/model/create-offer-form.model";
import { ImageUploader } from '../image-uploader/image-uploader';

const createOfferForm: CreateOfferFormStateModel = {
    dealerDataForm: undefined,
    offerImages: undefined,
    priceDataForm:undefined,
    equipmentTypeForm: undefined,
    additionalTechnicalDataForm: undefined,
    vehicleDescription: undefined,
    technicalDataForm: undefined,
    vehicleType: undefined,
    basicInfo: undefined,
    mainFeatures: {
        imported: false,
        destroyed: false
    } 
} 
const stateOptions = [{label: 'Nie', value: false}, {label: 'Tak', value: true}];

export const CreateOfferFormComponent: React.FC = () => {
    const formik = useFormik({
        initialValues: {createOfferForm},
        validate: () => {
        },
        onSubmit: () => {
            formik.resetForm();
        }
    });
    const formikBasicInfoValues: BasicInfoForm | undefined = formik.values.createOfferForm.basicInfo;
    const formikMainFeaturesValues: MainFeaturesForm | undefined = formik.values.createOfferForm.mainFeatures;
    const formikTechnicalDataValues: TechnicalDataForm | undefined = formik.values.createOfferForm.technicalDataForm;
    const formikVehicleDescriptionValues: VehicleDescriptionForm | undefined = formik.values.createOfferForm.vehicleDescription;
    const formikPriceDataValues: PriceDataForm | undefined = formik.values.createOfferForm.priceDataForm;
    const formikDealerDataForm: DealerDataForm | undefined = formik.values.createOfferForm.dealerDataForm;


    return <div className="create-offer-form-wrapper">
        <div className="title">
            
        </div>

        <div className="vehicle-details">
            <h1>Dane pojazdu</h1> 

            <div className="main-features">
                <form>
                    <h2>Cechy główne</h2>
                    <div className="row">
                        <h3>Uszkodzony</h3>
                        <SelectButton
                            options={stateOptions}
                            value={formikMainFeaturesValues?.destroyed}
                            className='main-feature-button'
                            onChange={() => formik.setFieldValue('createOfferForm.mainFeatures.destroyed', !formikMainFeaturesValues?.destroyed)}
                        />
                    </div>
                    <div className="row">
                        <h3>Importowany</h3>
                        <SelectButton
                            options={stateOptions}
                            value={formikMainFeaturesValues?.imported}
                            className='main-feature-button'
                            onChange={() => formik.setFieldValue('createOfferForm.mainFeatures.imported', !formikMainFeaturesValues?.imported)}
                        />
                    </div>
                </form>
            </div>

            <div className="basic-info">
                <h2>Informacje podstawowe</h2>
                <form>
                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="vin"
                                name="vin"
                                value={formikBasicInfoValues?.vin}
                            />
                            <label htmlFor="vin">VIN</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="mileage"
                                name="mileage"
                                value={formikBasicInfoValues?.mileage}
                            />
                            <label htmlFor="mileage">Przebieg</label>
                        </span>
                    </div>
                </form>
            </div>

            <div className="technical-data">
                <h2>Dane techniczne</h2>
                <form>
                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="yearOfProduction"
                                name="yearOfProduction"
                                value={formikTechnicalDataValues?.yearOfProduction}
                            />
                            <label htmlFor="yearOfProduction">Rok produkcji</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="brand"
                                name="brand"
                                value={formikTechnicalDataValues?.brand}
                            />
                            <label htmlFor="brand">Marka pojazdu</label>
                        </span>
                    </div>

                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="model"
                                name="model"
                                value={formikTechnicalDataValues?.model}
                            />
                            <label htmlFor="model">Model pojazdu</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="fuelType"
                                name="fuelType"
                                value={formikTechnicalDataValues?.fuelType}
                            />
                            <label htmlFor="fuelType">Rodzaj paliwa</label>
                        </span>
                    </div>

                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="horsePower"
                                name="horsePower"
                                value={formikTechnicalDataValues?.horsePower}
                            />
                            <label htmlFor="horsePower">Moc</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="engineCapacity"
                                name="engineCapacity"
                                value={formikTechnicalDataValues?.engineCapacity}
                            />
                            <label htmlFor="engineCapacity">Pojemność skokowa</label>
                        </span>
                    </div>

                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="numberOfDoors"
                                name="numberOfDoors"
                                value={formikTechnicalDataValues?.numberOfDoors}
                            />
                            <label htmlFor="numberOfDoors">Liczba drzwi</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="transmission"
                                name="transmission"
                                value={formikTechnicalDataValues?.transmission}
                            />
                            <label htmlFor="transmission">Skrzynia biegów</label>
                        </span>
                    </div>

                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="version"
                                name="version"
                                value={formikTechnicalDataValues?.version}
                            />
                            <label htmlFor="version">Wersja</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="generation"
                                name="generation"
                                value={formikTechnicalDataValues?.generation}
                            />
                            <label htmlFor="generation">Generacja</label>
                        </span>
                    </div>

                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="bodyType"
                                name="bodyType"
                                value={formikTechnicalDataValues?.bodyType}
                                />
                            <label htmlFor="bodyType">Typ nadwozia</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="color"
                                name="color"
                                value={formikTechnicalDataValues?.color}
                            />
                            <label htmlFor="color">Kolor</label>
                        </span>
                    </div>
                </form>
            </div>

            <div className="image-form">
                <h2>Zdjęcia</h2>
                <ImageUploader></ImageUploader>
            </div>      

            <div className="vehicle-description">
                <h2>Dane techniczne</h2>
                <form>
                    <span className="p-float-label">
                        <InputText 
                            id="title"
                            name="title"
                            value={formikVehicleDescriptionValues?.title}
                        />
                        <label htmlFor="title">Tytuł ogłoszenia</label>
                    </span>

                    <span className="p-float-label">
                        <InputTextarea
                            rows={8}
                            id="description"
                            name="description"
                            value={formikVehicleDescriptionValues?.description}
                            autoResize />
                        <label htmlFor="description">Opis pojazdu</label>
                    </span>
                </form>
            </div>

            <div className="additional-properties">
                <h2>Wyświetl dodatkowe szczegóły</h2>
                {/* <additional-properties></additional-properties> */}
            </div>

            <div className="price">
                <h2>Cena</h2>
                <form>
                    <div className="row">
                        <h3>Cena netto</h3>
                        <SelectButton
                            options={stateOptions}
                            value={formikPriceDataValues?.net}
                            className='net-button'
                            onChange={() => formik.setFieldValue('createOfferForm.priceDataForm.net', !formikPriceDataValues?.net)}
                        />
                    </div>

                    <div className="price-input-row">
                        <span className="p-float-label">
                            <InputText 
                                id="price"
                                name="price"
                                value={formikPriceDataValues?.price}
                            />
                            <label htmlFor="price">Cena</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="currency"
                                name="currency"
                                value={formikPriceDataValues?.currency}
                            />
                            <label htmlFor="currency">Waluta</label>
                        </span>
                    </div>
                </form>
            </div>

            <div className="dealer-data">
                <h2>Dane sprzedającego</h2>
                <form>
                    <div className="row">
                        <span className="p-float-label">
                            <InputText 
                                id="name"
                                name="name"
                                value={formikDealerDataForm?.name}
                            />
                            <label htmlFor="currency">Imię</label>
                        </span>

                        <span className="p-float-label">
                            <InputText 
                                id="address"
                                name="address"
                                value={formikDealerDataForm?.address}
                            />
                            <label htmlFor="currency">Adres</label>
                        </span>
                    </div>

                    <div className="half-row">
                        <span className="p-float-label"> 
                            <InputText 
                                id="phoneNumber"
                                name="phoneNumber"
                                value={formikDealerDataForm?.phoneNumber}
                                />
                            <label htmlFor="phoneNumber">Numer telefonu</label>
                        </span>
                    </div>
                </form>
            </div>
        </div>
    </div>   
}

// Aplikacja/AngularApp/oto-auto/src/components/forms/create-offer-form/create-offer-form.component.ts
import { Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'create-offer-form',
  templateUrl: './create-offer-form.component.html',
  styleUrls: ['./create-offer-form.component.css'],
})
export class CreateOfferFormComponent {
    stateOptions: any[] = [{label: 'Nie', value: false}, {label: 'Tak', value: true}];
    stateOptions2: any[] = [{label: 'Nie', value: false}, {label: 'Tak', value: true}];
    stateOptions3: any[] = [{label: 'Nie', value: false}, {label: 'Tak', value: true}];
    value: boolean = false;
    value2: boolean = false;
    value3: boolean = false;
    form = new FormGroup({
        vehicleType: new FormControl(),
        destroyed: new FormControl(),
        imported: new FormControl(),
        vin: new FormControl(),
        mileage: new FormControl(),
        yearOfProduction: new FormControl(),
        brand: new FormControl(),
        model: new FormControl(),
        fuelType: new FormControl(),
        horsepower: new FormControl(),
        engineCapacity: new FormControl(),
        numberOfDoors: new FormControl(),
        transmission: new FormControl(),
        version: new FormControl(),
        generation: new FormControl(),
        bodyType: new FormControl(),
        color: new FormControl(),
        title: new FormControl(),
        description: new FormControl(),
        price: new FormControl(),
        currency: new FormControl(),
        name: new FormControl(),
        address: new FormControl(),
        phoneNumber: new FormControl(),
        net: new FormControl(),
    })
}

<div class="wrapper">
    <form [formGroup]="form!">
        <div class="title">
            <h1>Stwórz ogłoszenie</h1> 
            <p-dropdown formControlName="vehicleType" [style]="{'width':'100%'}"  inputId="vehicleType" placeholder="Wybierz rodzaj pojazdu"></p-dropdown>
        </div>

        <div class="vehicle-details">
            <h1>Dane pojazdu</h1>

            <div class="main-features">
                <h2>Cechy główne</h2>
                <div class="row">
                    <h3>Uszkodzony</h3>
                    <p-selectButton styleClass="main-feature-button" formControlName="destroyed" [options]="stateOptions" [(ngModel)]="value"></p-selectButton>
                </div>
                <div class="row">
                    <h3>Importowany</h3>
                    <p-selectButton formControlName="imported" [options]="stateOptions2" [(ngModel)]="value2"></p-selectButton>
                </div>
            </div>

            <div class="basic-info">
                <h2>Informacje podstawowe</h2>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="vin" formControlName="vin" />
                        <label htmlFor="vin">VIN</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="mileage" formControlName="mileage" />
                        <label htmlFor="mileage">Przebieg</label>
                    </span>
                </div>
            </div>

            <div class="technical-data">
                <h2>Dane techniczne</h2>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="yearOfProduction" formControlName="yearOfProduction" />
                        <label htmlFor="yearOfProduction">Rok produkcji</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="brand" formControlName="brand" />
                        <label htmlFor="brand">Marka pojazdu</label>
                    </span>
                </div>

                <div class="row">                      
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="model" formControlName="model" />
                        <label htmlFor="model">Model pojazdu</label>
                    </span>

                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="fuelType" formControlName="fuelType" />
                        <label htmlFor="fuelType">Rodzaj paliwa</label>
                    </span>
                </div>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="horsepower" formControlName="horsepower" />
                        <label htmlFor="horsepower">Moc</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="engineCapacity" formControlName="engineCapacity" />
                        <label htmlFor="engineCapacity">Pojemność skokowa</label>
                    </span>
                </div>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="numberOfDoors" formControlName="numberOfDoors" />
                        <label htmlFor="numberOfDoors">Liczba drzwi</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="transmission" formControlName="transmission" />
                        <label htmlFor="transmission">Skrzynia biegów</label>
                    </span>
                </div>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="version" formControlName="version" />
                        <label htmlFor="version">Wersja</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="generation" formControlName="generation" />
                        <label htmlFor="generation">Generacja</label>
                    </span>
                </div>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="bodyType" formControlName="bodyType" />
                        <label htmlFor="bodyType">Typ nadwozia</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="color" formControlName="color" />
                        <label htmlFor="color">Kolor</label>
                    </span>
                </div>
            </div>


            <div class="image-form">
                <h2>Zdjęcia</h2>
                <image-uploader></image-uploader>
            </div>

            <div class="vehicle-description">
                <h2>Opis pojazdu</h2>
                            
                <span class="p-float-label">
                    <input [style]="{'width':'100%'}"  pInputText id="title" formControlName="title" />
                    <label htmlFor="title">Tytuł ogłoszenia</label>
                </span>
                    
                <span class="p-float-label">
                    <textarea  rows="8" [style]="{'width':'100%'}" pInputTextarea id="description" formControlName="description" [autoResize]="true"></textarea>
                    <label htmlFor="description">Opis pojazdu</label>
                </span>
            </div>


            <div class="additional-properties">
                <h2>Wyświetl dodatkowe szczegóły</h2>

                <additional-properties></additional-properties>
            </div>


            <div class="price">
                <h2>Cena</h2>
                <div class="row">
                    <h3>Cena netto</h3>
                    <p-selectButton styleClass="net-button" formControlName="net" [options]="stateOptions3" [(ngModel)]="value3"></p-selectButton>
                </div>

                <div class="price-input-row">
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="price" formControlName="price" />
                        <label htmlFor="price">Cena</label>
                    </span>

                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="currency" formControlName="currency" />
                        <label htmlFor="currency">Waluta</label>
                    </span>
                </div>
            </div>

            <div class="dealer-data">
                <h2>Dane sprzedającego</h2>

                <div class="row">
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}" pInputText id="name" formControlName="name" />
                        <label htmlFor="name">Twoje imię</label>
                    </span>

                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="address" formControlName="address" />
                        <label htmlFor="address">Adres</label>
                    </span>
                </div>

                <div class="half-row">
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="phoneNumber" formControlName="phoneNumber" />
                        <label htmlFor="phoneNumber">Numer telefonu</label>
                    </span>
                </div>
            </div>
        </div>
    </form>
</div>
