// Aplikacja/AngularApp/oto-auto/src/components/awarded-offer/awarded-offer.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { OfferCardComponentModel } from 'src/store/offer/offer-card-component.model';

@Component({
  selector: 'awarded-offer',
  templateUrl: './awarded-offer.component.html',
  styleUrls: ['./awarded-offer.component.css'],
})
export class AwardedOfferComponent {
  @Input() offer?: OfferCardComponentModel;

  constructor(private _router: Router) {}

  onOfferClick(): void {
    this._router.navigateByUrl('/offer/' + this.offer?.offerId);
  } 
}

<div class="offer-content"
    *ngIf="offer"
    (click)="onOfferClick()">
    <img 
        class="car-pic"
        src="{{'data:image/jpg;base64,' + offer.offerMainImage.imageBytes}}" 
        alt="car">
    <span 
        class="offer-name">
        {{ offer.offerTitle }}
    </span>
    <div class="offer-info">
        <span> {{ offer.yearOfProduction }} </span>
        <span> {{ offer.mileage + " " + offer.mileageUnit }} </span>
        <span> {{ offer.fuelType }} </span>
        <span> {{ offer.engineCapacity + "cm3" }} </span>
    </div>
    <span class="offer-price">
         {{ offer.offerPrice + " " + offer.offerCurrency }} 
    </span>
</div>

// Aplikacja/ReactApp/oto-auto/src/components/awarded-offer/awarded-offer.tsx
import { NavigateFunction, useNavigate } from 'react-router-dom'
import { OfferCardComponentModel } from '../../redux/model/offer-card-component.model'
import './awarded-offer.scss'

export const AwardedOffer: React.FC<{offer:OfferCardComponentModel}> = ({offer}) => {
    const navigate: NavigateFunction = useNavigate();
    
    if (!offer) {
        return <></>
    }

    return <>
        <div
            className="offer-content" 
            onClick={() => onOfferClick(navigate, offer.offerId)} >
            <img 
                className="car-pic"
                src={`data:image/jpeg;base64,${offer.offerMainImage.imageBytes}`} 
                alt="car" />
            <span 
                className="offer-name">
                { offer.offerTitle }
            </span>
            <div className="offer-info">
                <span> { offer.yearOfProduction } </span>
                <span> { offer.mileage + " " + offer.mileageUnit } </span>
                <span> { offer.fuelType } </span>
                <span> { offer.engineCapacity + "cm3" } </span>
            </div>
            <span className="offer-price">
                { offer.offerPrice + " " + offer.offerCurrency } 
            </span>
        </div>
    </>
}

function onOfferClick(navigate: NavigateFunction, offerId: number): void {
    navigate('/offer/' + offerId)
}
