// Aplikacja/ReactApp/oto-auto/src/app/App.tsx
import { BrowserRouter, Route, Routes } from 'react-router-dom'
import { MainPage } from '../pages/main-page'
import './App.scss'
import { NavbarComponent } from '../components/navbar/navbar'

function App() {
  return (
  <>
    <div className='root'>
      <NavbarComponent />
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<MainPage/>} />
        </Routes>
      </BrowserRouter>
    </div> 
  </>
  )
}

export default App

// Aplikacja/VueApp/oto-auto/src/App.vue
<script lang="ts">
    import MainPage from './pages/main/MainPage.vue';
    import { defineComponent } from 'vue';
    import Navbar from './components/navbar/Navbar.vue'

    export default defineComponent({
        name: 'App',
        components: {
            MainPage,
            Navbar
        },
        setup() {
            
        }
    })
</script>

<template>
    <div class="root">
        <Navbar />
        <router-view />
    </div>
</template>

<style scoped>
    .root {
        width: 100%;
        height: fit-content;
        background-color: var(--secondary-100);
        padding-top: 5vh;
    }

</style>
