// Aplikacja/ReactApp/oto-auto/src/components/create-offer-footer/create-offer-footer.tsx
import { Button } from 'primereact/button';
import './create-offer-footer.scss'


export const CreateOfferFooter: React.FC = () => {

    const createOffer = () => {

    }

    return <div className='wrapper'>
        <div className="button-wrapper">
            <Button 
                onClick={createOffer}
                label="Dodaj ogłoszenie"
                className='create-offer'    
            ></Button>
        </div>
    </div>;
}

// Aplikacja/AngularApp/oto-auto/src/components/create-offer-footer/create-offer-footer.component.ts
import { Component } from "@angular/core";

@Component({
    selector: 'create-offer-footer',
    templateUrl: './create-offer-footer.component.html',
    styleUrls: ['./create-offer-footer.component.css'],
})
export class CreateOfferFooterComponent {
    
}
<div class="wrapper">
    <p-button class="create-offer" label="Dodaj ogłoszenie"></p-button>
</div>
