// Aplikacja/VueApp/oto-auto/src/pages/create-offer/CreateOfferPage.vue
<script lang="ts">
import { defineComponent } from 'vue';


    export default defineComponent({
        name: "CreateOfferPage",
        components: {}
    })
</script>

<template>
    <div class="create-offer-wrapper">
        <div class="form-component">
 
            <div class="footer">
                
            </div>
        </div>

        <div class="tips-component">
            
        </div>
    </div>
</template>

<style scoped lang="scss">

</style>

// Aplikacja/ReactApp/oto-auto/src/pages/create-offer/create-offer.page.tsx
import './create-offer.page.scss'


export const CreateOfferPage: React.FC = () => {
    

    return <>
        <div className="create-offer-wrapper">
            <div className="form-component">
                {/* <create-offer-form></create-offer-form> */}

                <div className="footer">
                    {/* <create-offer-footer></create-offer-footer> */}
                </div>    
            </div>

            <div className="tips-component">

            </div>
        </div>
    </>;
}
