// Aplikacja/AngularApp/oto-auto/src/components/forms/additional-properties/additional-properties.component.ts
import { Component, OnInit } from "@angular/core";
import { Select, Store } from "@ngxs/store";
import { Observable } from "rxjs";
import { EquipmentType } from "src/api/models/equipment-type";
import { GetEquipmentTypes } from "src/store/actions/equipment-actions";
import { EquipmentSelector } from "src/store/selectors/equipment.selector";


@Component({
    selector: 'additional-properties',
    templateUrl: './additional-properties.component.html',
    styleUrls: ['./additional-properties.component.css'],
})
export class AdditionalPropertiesComponent implements OnInit {

    stateOptions: any[] = [{label: 'Nie', value: false}, {label: 'Tak', value: true}];
    value: boolean = false;

    @Select(EquipmentSelector.equipmentTypes)
    equipmentTypes$!: Observable<EquipmentType[]>;

    constructor(private _store: Store) {}
    
    ngOnInit(): void {
        this._store.dispatch(new GetEquipmentTypes());
    }

}
<div class="additional-properties-wrapper">
    <p-accordion [multiple]="true">
        <p-accordionTab header="Dane techniczne" iconPos="end">
            <div class="technical-data">
                <div class="row">
                    <h3>Kierownica po prawej (anglik)</h3>
                    <p-selectButton 
                        styleClass="techincal-data-button"
                        [options]="stateOptions"
                        [(ngModel)]="value"></p-selectButton>
                </div>
            </div>

            <div class="additional-technical-data">
                <div class="row">                      
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="drive" />
                        <label htmlFor="model">Napęd</label>
                    </span>

                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="emission" />
                        <label htmlFor="emission">Emisja CO2</label>
                    </span>
                </div>

                <div class="row">                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="colorType"/>
                        <label htmlFor="colorType">Rodzaj koloru</label>
                    </span>
                    
                    <span class="p-float-label">
                        <input [style]="{'width':'100%'}"  pInputText id="numberOfSeats" />
                        <label htmlFor="numberOfSeats">Liczba miejsc</label>
                    </span>
                </div>
            </div>
        </p-accordionTab>
        <p-accordionTab header="Wyposażenie" iconPos="end">
            <div class="equipment-wrapper">
                <p-accordion [multiple]="true">
                    <ng-container *ngFor="let equipmentType of equipmentTypes$ | async">
                        <p-accordionTab iconPos="end" header="{{ equipmentType.type }}">
                            <ng-container class="equipment-wrapper" *ngFor="let equipment of equipmentType.equipments ">
                                <div class="equipment-checkbox-wrapper">
                                    <p-checkbox inputId="equipment-name"></p-checkbox>
                                     <label for="equipment-name">{{ equipment.name }}</label>
                                </div>  
                            </ng-container>
                        </p-accordionTab>
                    </ng-container>
                </p-accordion>

            </div>
        </p-accordionTab>
        <p-accordionTab header="Historia" iconPos="end">
        </p-accordionTab>
    </p-accordion>
</div>

// Aplikacja/ReactApp/oto-auto/src/components/forms/additional-properties/additional-properties.component.tsx
import './additional-properties.component.scss'
import { useFormik } from 'formik';
import { Accordion, AccordionTab } from 'primereact/accordion';
import { InputText } from 'primereact/inputtext';
import { SelectButton } from 'primereact/selectbutton';
import { AdditionalPropertiesFormModel, Equipment, EquipmentForm, EquipmentItemsForm, EquipmentType, EquipmentValuesForm } from '../../../redux/model/create-offer-form.model';
import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { ThunkDispatch } from 'redux-thunk';
import { AnyAction } from '@reduxjs/toolkit/react';
import { RootState } from '../../../redux/store/store';
import { getEquipmentTypes } from '../../../redux/state/equipmentSlice';

const stateOptions: any[] = [{label: 'Nie', value: false}, {label: 'Tak', value: true}];

const additionalProperties: AdditionalPropertiesFormModel = {
    additionalTechnicalDataForm: undefined,
    equipmentForm: undefined,
    technicalDataForm: undefined
} 


export const AdditionalProperties: React.FC = () => {
    const equipmentTypes: EquipmentType[] = useSelector((state: RootState) => state.equipmentType.equipmentTypes)
    const dispatch = useDispatch<ThunkDispatch<RootState, undefined, AnyAction>>();

    useEffect(() => {
        dispatch(getEquipmentTypes())
    }, [dispatch])
    
    useEffect(() => {
        if (!equipmentTypes || equipmentTypes.length == 0) {
            return;
        }
        const equipmentForms: EquipmentForm[] = [];
        equipmentTypes.forEach((equipmentType: EquipmentType) => {
            equipmentForms.push(createEquipmentForm(equipmentType));
        })

        formik.setFieldValue("additionalProperties.equipmentForm", equipmentForms)
    }, [equipmentTypes])

    const formik = useFormik({
        initialValues: {additionalProperties},
        validate: () => {
        },
        onSubmit: () => {
            formik.resetForm();
        }
    });

    const equipmentFormik: EquipmentForm[] | undefined = formik.values.additionalProperties.equipmentForm;

    const createEquipmentForm = (equipmentType: EquipmentType) => {
        const equipmentValues: EquipmentValuesForm = {
            values: []
        }

        const equipmentForm: EquipmentForm = {
            type: equipmentType.type,
            equipments: equipmentValues 
        }
        const array: EquipmentItemsForm[] = []
        equipmentType.equipments.forEach((equipment: Equipment) => {
            array.push({
                id: equipment.id,
                name: equipment.name,
                value: false
            })
        })

        equipmentValues.values = array
        return equipmentForm
    }

    const handleEquipmentValueChange = (indexForm: number, eqIndex: number, value: boolean) => {
        const updatedEquipmentFormik = [...equipmentFormik!];
        updatedEquipmentFormik[indexForm].equipments.values[eqIndex].value = value;
        formik.setFieldValue('additionalProperties.equipmentForm', updatedEquipmentFormik);
    }

    return <div className="additional-properites-wrapper">
        <Accordion multiple>
            <AccordionTab header="Dane techniczne">
                <form>
                    <div className="technical-data">
                        <div className="row">
                            <h3>Kierownica po prawej (anglik)</h3>
                            <SelectButton
                                className="technical-data-button"
                                options={stateOptions}
                            ></SelectButton>
                        </div>
                    </div>
                </form>

                <form>
                    <div className="additional-technical-data">
                        <div className="row">
                            <span className="p-float-label">
                                <InputText 
                                    id="drive"
                                    value={additionalProperties.additionalTechnicalDataForm?.drive}
                                />
                                <label htmlFor="drive">Napęd</label>
                            </span>

                            <span className="p-float-label">
                                <InputText 
                                    id="emission"
                                    value={additionalProperties.additionalTechnicalDataForm?.emission}
                                />
                                <label htmlFor="emission">Emisja CO2</label>
                            </span>
                        </div>

                        <div className="row">
                            <span className="p-float-label">
                                <InputText 
                                    id="colorType"
                                    value={additionalProperties.additionalTechnicalDataForm?.colorType}
                                />
                                <label htmlFor="colorType">Rodzaj koloru</label>
                            </span>

                            <span className="p-float-label">
                                <InputText 
                                    id="numberOfSeats"
                                    value={additionalProperties.additionalTechnicalDataForm?.numberOfSeats}
                                />
                                <label htmlFor="numberOfSeats">Liczba miejsc</label>
                            </span>
                        </div>
                    </div>
                </form>
            </AccordionTab>

            <AccordionTab header="Wyposażenie">
                <div className="equipment-wrapper">
                    <form>
                        <Accordion multiple>
                            { equipmentFormik && equipmentFormik.map((eq: EquipmentForm, indexForm: number) => 
                                <AccordionTab key={indexForm} header={eq.type} >
                                    <div className="equipment-checkbox-wrapper">
                                        {eq.equipments.values.map((equipment: EquipmentItemsForm, eqIndex: number) => 
                                            <div key={eqIndex} className='equipment-checkbox'>
                                                <input 
                                                    type='checkbox'
                                                    checked={equipment.value}
                                                    onChange={(e) => {handleEquipmentValueChange(indexForm, eqIndex, e.target.checked)}}
                                                />
                                                <label>
                                                    {equipment.name}
                                                </label>
                                            </div>
                                        )}
                                    </div>
                                </AccordionTab>
                            )}
                        </Accordion>
                    </form>
                </div>
            </AccordionTab>
            <AccordionTab header="Historia"></AccordionTab>
        </Accordion>
    </div>
}
