// Aplikacja/AngularApp/oto-auto/src/components/vehicle-images-gallery/vehicle-images-gallery.component.ts
import { Component } from '@angular/core';
import { Select } from '@ngxs/store';
import { Observable } from 'rxjs';
import { OfferImage } from 'src/store/offer/offer-image.model';
import { OffersSelector } from 'src/store/offer/offers.selector';

@Component({
  selector: 'vehicle-images-gallery',
  templateUrl: './vehicle-images-gallery.component.html',
  styleUrls: ['./vehicle-images-gallery.component.css'],
})
export class VehicleImagesGalleryComponent {
    @Select(OffersSelector.vehicleImages)
    vehicleImages$!: Observable<OfferImage[]>;
}


<div class="gallery-wrapper">
    <p-galleria 
        [value]="(vehicleImages$ | async) || undefined" 
        [containerStyle]="{ 'max-width': '700px', 'max-height': '500px' }"
        [showItemNavigators]="true"
        [numVisible]="4"
    >
        <ng-template pTemplate="item" let-item>
            <img  style="object-fit: contain;" src="{{'data:image/jpg;base64,' + item.imageBytes}}" width="550" height="400"/>
        </ng-template>
        <ng-template pTemplate="thumbnail" let-item>
            <div class="grid grid-nogutter justify-content-center">
                <img class="gallery-image" src="{{'data:image/jpg;base64,' + item.imageBytes}}" width="150" height="100"  />
            </div>
        </ng-template>
    </p-galleria>
</div>

// Aplikacja/ReactApp/oto-auto/src/components/vehicle-images-gallery/vehicle-images-gallery.tsx
import './vehicle-images-gallery.scss'
import { Galleria } from 'primereact/galleria';
import { OfferImage } from '../../models/offer-image';


export const VehicleImagesGalleryComponent: React.FC<{vehicleImages: OfferImage[]}> = ({vehicleImages}) => {
    const itemTemplate = (item: OfferImage) => {
        return <img className='main-gallery-image' src={'data:image/jpg;base64,' + item.imageBytes } style={{ width: '550px', height: '400px' }} />
    }

    const thumbnailTemplate = (item: OfferImage) => {
        return <div className="grid grid-nogutter justify-content-center">
            <img className='gallery-image' src={'data:image/jpg;base64,' + item.imageBytes } style={{ width: '150px', height: '100px' }}  />
        </div>
    }

    return <>    
        <div className="gallery-wrapper">
            <Galleria 
                style={{ maxWidth: '700px', maxHeight: '500px' }}
                value={vehicleImages} 
                numVisible={4} 
                item={itemTemplate}
                thumbnailsPosition={'bottom'}
                thumbnail={thumbnailTemplate}
                showItemNavigators
                />
        </div>
    </>
}
