// Aplikacja/ReactApp/oto-auto/src/pages/main/main-page.tsx
import React from "react"
import './main-page.scss'
import { MainSearchEngineComponent } from "../../components/main-search-engine/main-search-engine"
import { AwardedOfferGridComponent } from "../../components/awarded-offer-grid/awarded-offer-grid"


export const MainPage: React.FC = () => {

    return <>
        <div className="main-page-container">
            <div className="search-engine">
                <MainSearchEngineComponent />
            </div>

            <div className="awarded-offers">
                <AwardedOfferGridComponent />
            </div>
        </div>
    </>
}

// Aplikacja/AngularApp/oto-auto/src/pages/main/main-page.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'main-page',
  templateUrl: './main-page.component.html',
  styleUrls: ['./main-page.component.css'],
})
export class MainPageComponent {}

<div class="container">
    <div class="search-engine">
        <main-search-engine></main-search-engine>
    </div>

    <div class="awarded-offers">
        <awarded-offer-grid></awarded-offer-grid>
    </div>
</div>
