// Aplikacja/AngularApp/oto-auto/src/components/offer-view-price/offer-view-price.component.ts
import { Component } from "@angular/core";
import { Select } from "@ngxs/store";
import { Observable } from "rxjs";
import { OfferActivityComponentModel } from "src/store/offer/offer-card-component.model";
import { OffersSelector } from "src/store/offer/offers.selector";

@Component({
    selector: 'offer-view-price',
    templateUrl: './offer-view-price.component.html',
    styleUrls: ['./offer-view-price.component.css'],
})
export class OfferViewPriceComponent {

    @Select(OffersSelector.offer)
    offer$!: Observable<OfferActivityComponentModel>
    

    getNumberFromString(num: string): number {
        return parseInt(num.replace(" ", ""));
    }

    getLoanFromNumber(num: string): number {
        return Math.round(this.getNumberFromString(num) / 12)
    }
}
<div class="offer-view-price-wrapper" *ngIf="offer$ | async as offer">
    <div class="offer-title">
        <h2>
            {{ offer.offerTitle }}
        </h2>
    </div>

    <div class="offer-info">
        <span> {{ offer.yearOfProduction }} </span>
        <span> {{ offer.mileage }} </span>
        <span> {{ offer.fuelType }} </span>
        <span> {{ offer.engineCapacity }} </span>
    </div>

    <span class="offer-price"> {{ offer.offerPrice }} PLN </span>

    <div class="loan-wrapper" *ngIf="offer.offerPrice">
        <div class="value">
            Lub od <br>
            <span>
                {{ getNumberFromString(offer.offerPrice) / 12  }} PLN
            </span> /mc
        </div>

        <div>
            <p-button
                label="Sprawdź stawkę"
            ></p-button>
        </div>
    </div>
</div>

// Aplikacja/ReactApp/oto-auto/src/components/offer-view-price/offer-view-price.tsx
import { OfferActivityComponentModel } from '../../redux/model/offer-card-component.model'
import './offer-view-price.scss'
import { Button } from 'primereact/button'


export const OfferViewPriceComponent: React.FC<{offer: OfferActivityComponentModel}> = ({offer}) => {


    return <>
        <div className="offer-view-price-wrapper">
            <div className="offer-title">
                <h2>
                    { offer.offerTitle }
                </h2>
            </div>

            <div className="offer-info">
                <span> { offer.yearOfProduction } </span>
                <span> { offer.mileage } </span>
                <span> { offer.fuelType } </span>
                <span> { offer.engineCapacity } </span>
            </div>

            <span className="offer-price"> { offer.offerPrice } </span>

            <div className="loan-wrapper">
                <div className="value">
                    Lub od <br/>
                    <span>
                        { getLoanFromNumber(offer.offerPrice)  } PLN
                    </span> /mc
                </div>

                <div>
                    <Button label="Sprawdź stawkę" />
                </div>
            </div>
        </div>
    </>
}


function getNumberFromString(num: string): number {
    return parseInt(num.replace(" ", ""));
}

function getLoanFromNumber(num: string): number {
    return Math.round(getNumberFromString(num) / 12)
}
