// Aplikacja/AngularApp/oto-auto/src/components/offer-details/offer-details.component.ts
import { Component } from "@angular/core";
import { Select } from "@ngxs/store";
import { Observable } from "rxjs";
import { VehicleDetailsRow } from "src/store/model/vehicle-details-row.model";
import { OffersSelector } from "src/store/offer/offers.selector";

@Component({
    selector: 'offer-details',
    templateUrl: './offer-details.component.html',
    styleUrls: ['./offer-details.component.css'],
})
export class OfferDetailsComponent {

    @Select(OffersSelector.offerDetails)
    offerDetails$!: Observable<VehicleDetailsRow[]>
}
<div class="offer-details-wrapper">
    <h2 class="title">Szczegóły</h2>
    <div class="vehicle-details-wrapper">
        <div *ngFor="let row of offerDetails$ | async" class="vehicle-details-row">
            <span class="attribute">{{ row.attribute }}</span>
            <span class="value">{{ row.value }}</span>
        </div>
    </div>
</div>

// Aplikacja/ReactApp/oto-auto/src/components/offer-details/offer-details.tsx
import React from 'react'
import './offer-details.scss'
import { VehicleDetailsRow } from '../../models/vehicle-details-row'

export const OfferDetailsComponent: React.FC<{vehicleAttributes: VehicleDetailsRow[]}> = ({vehicleAttributes}) => {
    // const [offerDetails, setOfferDetails] = useState<VehicleDetailsRow[]>([])

    return <>
        <div className="offer-details-wrapper">
            <h2 className="title">Szczegóły</h2>
            <div className="vehicle-details-wrapper">
                {
                    vehicleAttributes && vehicleAttributes.map(
                        (row: VehicleDetailsRow) => (
                            <div  className="vehicle-details-row">
                                <span className="attribute">{ row.attribute } </span>
                                <span className="value">{ row.value }</span>
                            </div>   
                        )
                    )
                }
            </div>
        </div>
    </>
}
