// Aplikacja/ReactApp/oto-auto/src/components/navbar/navbar.tsx
import React from "react"
import './navbar.scss'
import { NavigateFunction, useNavigate } from "react-router-dom"

export const NavbarComponent: React.FC = () => {
    const navigate: NavigateFunction = useNavigate();

    return <>
        <nav className="navigation">
            <div className="logo">
                OTOAUTO
            </div>

            <ul>
                <li>Aktualności</li>
                <li>Obserwowane</li>
                <li>Zaloguj się</li>
                <li onClick={() => onCreateOfferClick(navigate)}>Wystaw ogłoszenie</li>
            </ul>
        </nav>
    </>
}

function onCreateOfferClick(navigate: NavigateFunction): void  {
    navigate('/new-offer');
}

// Aplikacja/AngularApp/oto-auto/src/components/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css'],
})
export class NavbarComponent {
  
  constructor(private _router: Router) {}

  onCreateOfferClick(): void {
    this._router.navigateByUrl('/new-offer');
  } 
}

<nav class="navigation">
    <div class="logo">
        OTOAUTO
    </div>
    <ul>
        <li>Aktualności</li>
        <li>Obserwowane</li>
        <li>Zaloguj się</li>
        <li (click)="onCreateOfferClick()">Wystaw ogłoszenie</li>
    </ul>

</nav>
