// Aplikacja/AngularApp/oto-auto/src/components/awarded-offer-grid/awarded-offer-grid.component.ts
import { Component, OnInit } from '@angular/core';
import { Select, Store } from '@ngxs/store';
import { Observable } from 'rxjs';
import { GetAwardedOffers } from 'src/store/offer/offer-actions';
import { OfferCardComponentModel } from 'src/store/offer/offer-card-component.model';
import { OffersSelector } from 'src/store/offer/offers.selector';

@Component({
  selector: 'awarded-offer-grid',
  templateUrl: './awarded-offer-grid.component.html',
  styleUrls: ['./awarded-offer-grid.component.css']
})
export class AwardedOfferGridComponent implements OnInit {
  
  @Select(OffersSelector.offerCards)
  offers$!: Observable<OfferCardComponentModel[]>

  constructor(private _store: Store) {}

  ngOnInit(): void {
    this._store.dispatch(new GetAwardedOffers());
  }
}

<div class="wrapper">
    <span class="awarded-offers-label">Wyróżnione oferty</span>
    <div class="offers">
        <ng-container *ngFor="let offer of offers$ | async">
            <awarded-offer [offer]="offer"></awarded-offer>
        </ng-container>
    </div>
</div>

// Aplikacja/ReactApp/oto-auto/src/components/awarded-offer-grid/awarded-offer-grid.tsx
import { useEffect } from 'react'
import './awarded-offer-grid.scss'
import { OfferCardComponentModel } from '../../redux/model/offer-card-component.model'
import { AwardedOffer } from '../awarded-offer/awarded-offer'
import React from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { RootState } from '../../redux/store/store'
import { getAwardedOffers } from '../../redux/state/offerSlice'
import { ThunkDispatch } from 'redux-thunk'
import { AnyAction } from '@reduxjs/toolkit'


export const AwardedOfferGridComponent: React.FC = () => {     
    const offers: OfferCardComponentModel[] = useSelector((state: RootState) => state.offerCard.offerCardsComponent)
    const dispatch = useDispatch<ThunkDispatch<RootState, undefined, AnyAction>>();

    useEffect(() => {
        dispatch(getAwardedOffers())
    }, [dispatch])

    return <>
        <div className="awarderd-offer-grid-wrapper">
            <span className="awarded-offers-label">Wyróżnione oferty</span>
            <div className="offers">
                { offers && offers.length > 0 && offers.map(
                    (offer: OfferCardComponentModel) => (
                        <React.Fragment key={offer.offerId}>
                            <AwardedOffer offer={offer} />
                        </React.Fragment>
                    )
                )}    
            </div>
        </div>
    </>
}
